from pathlib import Path

path = Path('index.html')
html = path.read_text(encoding='utf-8')

if 'id="free-appraisal"' not in html:
    css = '''\n<style id="bzt-appraisal-style">\n.appraisal-hero{background:linear-gradient(135deg,#fff8e8,#fff);border:1px solid #ead7a3;border-radius:18px;padding:24px;margin:24px 0;box-shadow:0 4px 18px rgba(80,50,20,.06)}\n.appraisal-hero h2{margin:0 0 10px;color:#650000;font-size:25px}.appraisal-hero p{line-height:1.8;color:#555}.appraisal-btn{display:inline-block;background:linear-gradient(135deg,#650000,#a87508);color:#fff!important;text-decoration:none;padding:12px 20px;border-radius:999px;font-weight:800;margin-top:8px}.appraisal-points{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:16px 0}.appraisal-point{background:#fff;border-radius:12px;padding:13px;text-align:center;color:#650000;font-weight:700}.appraisal-page{max-width:850px;margin:25px auto;padding:0 16px}.upload-box{background:#fff;border-radius:18px;padding:22px;box-shadow:0 4px 18px rgba(80,50,20,.07);margin-bottom:16px}.upload-box h3{color:#650000;margin-top:0}.upload-box input,.upload-box textarea,.upload-box select{width:100%;padding:11px;border:1px solid #ddd;border-radius:10px;margin:6px 0 14px;box-sizing:border-box;font-size:15px}.photo-preview{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:10px}.photo-preview img{width:100%;aspect-ratio:1;object-fit:cover;border-radius:10px;border:1px solid #eee}.contact-box{background:#650000;color:#fff;border-radius:18px;padding:22px;text-align:center}.contact-box a{display:inline-block;background:#fff;color:#650000;text-decoration:none;padding:11px 18px;border-radius:999px;font-weight:800;margin-top:8px}.small-note{font-size:12px;color:#888;line-height:1.7}@media(max-width:650px){.appraisal-points{grid-template-columns:repeat(2,1fr)}.photo-preview{grid-template-columns:repeat(2,1fr)}}\n</style>\n'''
    html = html.replace('</head>', css + '</head>', 1)

    block = '''\n<section class="container" id="free-appraisal">\n<div class="appraisal-hero">\n<h2>🔎 免费钱币鉴定 · 在线估价</h2>\n<p><strong>不知道手里的钱币是什么？值多少钱？是否值得评级？</strong></p>\n<p>上传或准备钱币正面、背面、边齿等清晰照片，提供年代、重量、直径等信息，可获得初步收藏分析与估价咨询。</p>\n<div class="appraisal-points"><div class="appraisal-point">📷 照片鉴定</div><div class="appraisal-point">💰 免费估价</div><div class="appraisal-point">🏆 评级咨询</div><div class="appraisal-point">⏰ 24小时响应</div></div>\n<a class="appraisal-btn" href="appraisal.html">立即进入免费鉴定 →</a>\n</div>\n</section>\n'''
    marker = '<h2 class="section-title">📈 钱币行情 · 市场分析</h2>'
    if marker in html:
        html = html.replace(marker, block + '\n' + marker, 1)
    path.write_text(html, encoding='utf-8')

appraisal = '''<!DOCTYPE html>\n<html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>免费钱币鉴定 · 币智通 AI</title>\n<style>body{margin:0;background:#f7f3ed;color:#222;font-family:-apple-system,BlinkMacSystemFont,"PingFang SC","Microsoft YaHei",sans-serif}.appraisal-page{max-width:850px;margin:25px auto;padding:0 16px}.upload-box,.contact-box{background:#fff;border-radius:18px;padding:22px;margin-bottom:16px;box-shadow:0 4px 18px rgba(80,50,20,.07)}h1{color:#650000}h3{color:#650000}.upload-box input,.upload-box textarea,.upload-box select{width:100%;padding:11px;border:1px solid #ddd;border-radius:10px;margin:6px 0 14px;box-sizing:border-box;font-size:15px}.photo-preview{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.photo-preview img{width:100%;aspect-ratio:1;object-fit:cover;border-radius:10px}.contact-box{background:#650000;color:#fff;text-align:center}.contact-box a{display:inline-block;background:#fff;color:#650000;text-decoration:none;padding:11px 18px;border-radius:999px;font-weight:800;margin-top:8px}.back{color:#650000;text-decoration:none}@media(max-width:650px){.photo-preview{grid-template-columns:repeat(2,1fr)}}</style></head>\n<body><main class="appraisal-page"><a class="back" href="index.html">← 返回币智通 AI</a><h1>🔎 免费钱币鉴定</h1><div class="upload-box"><h3>第一步：选择钱币照片</h3><p>建议准备：正面、背面、边齿、局部细节照片。</p><input id="photos" type="file" accept="image/*" multiple><div id="preview" class="photo-preview"></div><p style="font-size:12px;color:#888;line-height:1.7">提示：当前网站为免费静态页面，照片只在你的手机/浏览器中预览，不会自动上传到服务器。为了保护隐私，请不要上传身份证、银行卡等无关资料。</p></div><div class="upload-box"><h3>第二步：补充藏品信息</h3><label>钱币类别</label><select><option>银元 / 银币</option><option>古钱币</option><option>纸币</option><option>金币</option><option>纪念币</option><option>机制币</option><option>评级币</option><option>其他</option></select><label>已知信息</label><textarea rows="5" placeholder="例如：正面文字、年份、重量、直径、来源、是否评级等"></textarea></div><div class="contact-box"><h3 style="color:#fff">第三步：免费咨询</h3><p>照片准备好后，请通过电话 / 微信发送照片，我们提供免费鉴定、咨询和线上估价。</p><p><strong style="font-size:24px">13799875350</strong></p><a href="tel:13799875350">📞 拨打 13799875350</a><p style="font-size:12px;opacity:.85;margin-top:14px">免费评估 · 无交易不收费 · 24小时响应 · 隐私保密</p></div></main><script>document.getElementById('photos').addEventListener('change',function(e){const box=document.getElementById('preview');box.innerHTML='';Array.from(e.target.files).slice(0,9).forEach(function(file){const img=document.createElement('img');img.src=URL.createObjectURL(file);box.appendChild(img)})});</script></body></html>\n'''
Path('appraisal.html').write_text(appraisal, encoding='utf-8')
print('免费鉴定入口已生成')
